// MIT License
//
// MEII - MAHI Exo-II Library
// Copyright (c) 2020 Mechatronics and Haptic Interfaces Lab - Rice University
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// Author(s): Craig McDonald (craig.g.mcdonald@gmail.com)

#pragma once

#include <vector>
#include <Mahi/Util/Math/Integrator.hpp>
#include <Mahi/Util/Timing/Time.hpp>
#include <MEII/Control/Trajectory.hpp>
#include <MEII/Control/WayPoint.hpp>
#include <Eigen/Dense>

namespace meii {

    class DynamicMotionPrimitive {

    public:

		/// Constructor without nonlinear function
		DynamicMotionPrimitive(const mahi::util::Time &sample_period, const WayPoint &start, const WayPoint &goal, double gamma = 25.0 / 3.0);

		/// Returns the trajectory generated by the DMP
        const Trajectory& trajectory();

		/// Updates the trajectory of the DMP based on the new value of theta
		const Trajectory& update(const std::vector<double> &theta);

		/// Clears the DMP memory
        void clear();

		/// Sets the start point and regenerates the trajectory. Returns true if successful.
		bool set_start(const WayPoint &start);

		/// Sets the goal point and regenerates the trajectory. Returns true if successful.
		bool set_goal(const WayPoint &goal);

		/// Sets the start point and goal point and regenerates the trajectory. Returns true if successful.
		bool set_endpoints(const WayPoint &start, const WayPoint &goal);

		/// Sets the interp_method and max_diff properties of the trajectory.
		void set_trajectory_params(Trajectory::Interp interp_method = Trajectory::Interp::Linear, const std::vector<double> &max_diff = { mahi::util::INF });

		/// Returns the value of the parameter gamma
		double get_gamma() const;

		/// Returns the value of the parameter tau
		double get_tau() const;

    private:

		/// Checks that input parameters start, goal, K, and D all have dimensions that are consistent
        bool check_param_dim();

		/// Sets the parameter tau based on given waypoints and generates a vector of waypoint times for the trajectory
		void set_timing_parameters();

		/// Generate trajectory from given parameters
		void generate_trajectory();


    private:
        
		mahi::util::Time Ts_; ///< sample period
        WayPoint q_0_; ///< starting point
		WayPoint g_; ///< goal point
        Eigen::MatrixXd K_; ///< stiffness matrix
        Eigen::MatrixXd D_; ///< damping matrix
		
		double gamma_; ///< rate parameter for decay of nonlinear vector field
        double tau_; ///< temporal scaling factor ensuring arrival at the goal
        double s_; ///< phase variable that monotonically decreases from one to zero
		
        std::size_t path_dim_; ///< dimensionality of the trajectory
        std::size_t path_size_; ///< number of waypoints in the trajectory
        std::vector<double> times_; ///< vector of times associated with trajectory waypoints
		std::size_t current_time_idx_; ///< index for tracking generation of trajectory
		std::vector<mahi::util::Integrator> integrator_; ///< vector of integrators for integrating state equations
        
        Eigen::VectorXd q_0_mat_; ///< matrix for storing starting point position
		Eigen::VectorXd g_mat_; ///< matrix for storing goal point position
        Eigen::VectorXd q_mat_; ///< matrix for storing current states
        Eigen::VectorXd q_dot_mat_; ///< matrix for storing current first time derivative of states
		Eigen::VectorXd q_ddot_mat_; ///< matrix for storing current second time derivative of states
		Eigen::VectorXd theta_mat_; ///< matrix for storing current feature weighting vector

        Trajectory trajectory_; ///< trajectory generated upon construction or update of feature weighting vector theta

    };

} // namespace meii
